<a href="https://colab.research.google.com/github/hrahmia/My-Notebooks/blob/main/Semi_Supervised_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#For this task, I will perform semi-supervised learning and will establish a baseline performance

In [73]:
import numpy as np
import pandas as pd
import sklearn as skl
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.semi_supervised import LabelPropagation

In [19]:
# Defining the dataset
X, y = make_classification(n_samples=1000, n_features=2, n_informative=2, n_redundant=0, random_state=1)

In [20]:
# Spliting into train and test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50, random_state=1, stratify=y)

In [30]:
# printing the array and checking datatype
#print('Array:', X_train)
print('Datatype:', X_train.dtype)

Datatype: float64


### I will split the training dataset in half again into a portion that will have labels and a portion that we will pretend is unlabeled.

In [32]:
# Splitting train set into labeled and unlabeled
X_train_lab, X_test_unlab, y_train_lab, y_test_unlab = train_test_split(X_train, y_train,  test_size=0.50, random_state=1, stratify=y_train )

In [59]:
X_train_lab.shape

(250, 2)

In [62]:
print(np.unique(y_train_lab))

[0 1]


In [38]:
y_train.shape

(500,)

In [51]:
unique, counts = np.unique(y_train, return_counts=True)
print(unique)
print(counts)

[0 1]
[250 250]


###I will use logistic regration


In [57]:
# Defining the Model
model = LogisticRegression()

In [63]:
# Fitting Model on Labeld Data
model.fit(X_train_lab, y_train_lab)

LogisticRegression()

In [65]:
# Making Prediction on hold out test set
yhat = model.predict(X_test)

In [70]:
# Calculating the Score for test set
score = accuracy_score(y_test, yhat)

In [72]:
print('Accuracy: %.3f' % (score*100))

Accuracy: 84.800


# Applying Label Probagation for Semi_Supervised Learning

In [78]:
# Packages for Label Probagating

from sklearn import LabelProbagation


In [99]:
# Defining the Dataset
X, y = make_classification(n_samples=1000, n_features=2, n_informative=2, n_redundant=0, random_state=1)

In [100]:
X, y = make_classification(n_samples=1000, n_features=2, n_informative=2, n_redundant=0, random_state=1)

In [101]:
# Spliting Data into Train and Test Datasets
X_Train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50, random_state=1, stratify=y)

In [102]:
# Spliting into Labeled and Unlabeled Datasets
X_train_lab, X_test_unlab, y_train_lab, y_test_unlab = train_test_split(X_train, y_train, test_size=0.50, random_state=1, stratify=y_train)

In [103]:
from scipy.optimize.slsqp import concatenate
## This part is unique - Double Parantheses!
# Creating the Dataset Input
X_train_mixed = concatenate((X_train_lab, X_test_unlab))

In [106]:
y_test_unlab

array([1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0])

In [109]:
## This part is unique
# Creating "no label" for unlabeled data
nolabel = [-1 for _ in range(len(y_test_unlab))]

In [113]:
y_train_lab

array([0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1])

In [141]:
## This part is unique
# Recombine the training dataset labels
y_train_mixed = concatenate((y_train_lab, nolabel))

In [142]:
y_train_mixed

array([ 0,  0,  1,  1,  0,  1,  1,  0,  0,  1,  1,  1,  0,  0,  0,  1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  1,  1,  0,  1,  0,  1,
        0,  1,  0,  0,  1,  1,  1,  1,  1,  0,  0,  0,  0,  1,  1,  0,  1,
        1,  1,  1,  1,  1,  0,  1,  0,  1,  0,  0,  1,  0,  0,  0,  0,  1,
        1,  0,  1,  0,  1,  1,  0,  1,  1,  0,  1,  0,  1,  0,  0,  0,  1,
        1,  0,  1,  0,  1,  1,  1,  0,  0,  0,  1,  1,  1,  0,  0,  1,  1,
        1,  1,  0,  0,  1,  1,  0,  1,  0,  1,  1,  1,  1,  1,  0,  1,  0,
        0,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  0,  0,
        1,  1,  0,  0,  1,  1,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0,
        0,  1,  1,  0,  1,  1,  0,  0,  0,  1,  1,  0,  1,  1,  1,  0,  1,
        0,  1,  0,  1,  1,  0,  0,  1,  1,  0,  1,  0,  1,  0,  1,  1,  1,
        1,  1,  1,  0,  0,  0,  1,  1,  0,  0,  1,  1,  1,  1,  1,  0,  0,
        1,  0,  0,  1,  0,  1,  0,  1,  1,  0,  1,  1,  0,  1,  1,  0,  0,
        1,  0,  1,  1,  0

In [143]:
# Defining The Model
model = LabelPropagation()

In [144]:
# Fitting Model on Trainig Dataset
model.fit(X_train_mixed, y_train_mixed)

LabelPropagation()

In [145]:
# Making Prediction on Hold Out Test Set
yhat = model.predict(X_test)

In [146]:
# Calculating Score for Test Set
score = accuracy_score(y_test, yhat)

In [147]:
# Summarizing Score
print(f'Accuracy: %.3f ' % (score*100))

Accuracy: 85.600 


In the Example, The y_train_mixed data was not shuffled. Here i shuffled the Array

In [134]:
# Defining The Model
model = LabelPropagation()

In [133]:
# Shuffling "y_train_mixed" --> hra
hra = np.take(y_train_mixed,np.random.permutation(y_train_mixed.shape[0]),axis=0,out=y_train_mixed)

In [140]:
hra

array([-1,  1, -1,  1,  0,  0, -1,  0,  0, -1,  0, -1, -1, -1, -1, -1,  0,
       -1,  0, -1,  1,  1,  0,  1, -1, -1,  0,  1,  0, -1, -1, -1, -1,  0,
        0, -1,  0,  0, -1, -1,  0, -1, -1, -1, -1, -1, -1,  1,  1,  0,  0,
       -1,  1, -1, -1,  1, -1, -1,  1, -1, -1,  1, -1, -1, -1,  1,  0, -1,
       -1, -1, -1,  0, -1, -1,  0, -1,  1,  0, -1, -1,  1, -1, -1, -1,  1,
        1, -1, -1, -1, -1, -1,  0,  1, -1, -1, -1, -1, -1, -1,  0, -1,  0,
        1,  1, -1,  0,  1,  1,  0,  0, -1,  0,  0,  1,  0, -1, -1, -1,  0,
        1, -1,  1,  1, -1, -1,  0,  1,  1, -1, -1,  1,  1,  0, -1,  0, -1,
       -1,  1,  1,  0,  1, -1,  0,  0, -1, -1, -1,  1, -1,  1, -1,  1, -1,
       -1, -1, -1,  1, -1,  0,  0, -1,  0, -1, -1,  0,  0,  1,  0,  0, -1,
       -1, -1,  1,  1, -1, -1, -1, -1,  1,  0,  1, -1,  0,  1,  1, -1, -1,
       -1,  0, -1, -1, -1,  1, -1, -1, -1, -1,  1, -1, -1,  1,  1, -1,  0,
        1, -1,  0,  0, -1,  0,  0,  1, -1, -1,  1,  0, -1,  0, -1,  1, -1,
       -1,  0,  1, -1,  1

In [136]:
# Fitting Model on Trainig Dataset
model.fit(X_train_mixed, hra)

LabelPropagation()

In [137]:
# Making Prediction on Hold Out Test Set
yhat = model.predict(X_test)

In [138]:
# Calculating Score for Test Set
score = accuracy_score(y_test, yhat)

In [139]:
# Summarizing Score
print(f'Accuracy: %.3f ' % (score*100))

Accuracy: 48.200 


Another approach we can use with the semi-supervised model is to take the estimated labels for the training dataset and fit a supervised learning model.

In [148]:
# define model
model = LabelPropagation()
# fit model on training dataset
model.fit(X_train_mixed, y_train_mixed)
# get labels for entire training dataset data
tran_labels = model.transduction_
# define supervised learning model
model2 = LogisticRegression()
# fit supervised learning model on entire training dataset
model2.fit(X_train_mixed, tran_labels)
# make predictions on hold out test set
yhat = model2.predict(X_test)
# calculate score for test set
score = accuracy_score(y_test, yhat)
# summarize score
print('Accuracy: %.3f' % (score*100))

Accuracy: 86.200


With shuffled array...

In [149]:
# define model
model = LabelPropagation()
# fit model on training dataset
model.fit(X_train_mixed, hra)
# get labels for entire training dataset data
tran_labels = model.transduction_
# define supervised learning model
model2 = LogisticRegression()
# fit supervised learning model on entire training dataset
model2.fit(X_train_mixed, tran_labels)
# make predictions on hold out test set
yhat = model2.predict(X_test)
# calculate score for test set
score = accuracy_score(y_test, yhat)
# summarize score
print('Accuracy: %.3f' % (score*100))

Accuracy: 34.600
